### ISSUE TITLE
`convertDeltaToHtml` does not work with lists

### ISSUE THREAD

**Issue by kasparkallas** [joelcolucci/node-quill-converter#2]
When the output should be:
```
<ol>
  <li>first</li>
  <li>second</li>
</ol>
```
It is:
```
<ol>
  <li>first</li>
</ol>
<ol>
  <li>second</li>
</ol>
```
Demos with same Delta JSON:
https://runkit.com/embed/8f76i7a69m85
https://codepen.io/kasparkallas/pen/oPxyqZ

**Comment by joelcolucci** [comment]
Thanks for submitting this @kasparkallas. I'll review shortly and will be in touch.

**Comment by joelcolucci** [comment]
Thank you for your patience @kasparkallas.

## Background
Below is the source code for `convertDeltaToHtml`.
```js
function convertDeltaToHtml = (delta) => {
  QUILL.setContents(delta);

  let html = QUILL.root.innerHTML;
  return html;
};
```
## Research
Logging `quill.root.innerHTML` in the ["Quill Playground"](https://codepen.io/kasparkallas/pen/oPxyqZ?editors=1111) logs the **expected** HTML. 

However when running using `node-quill-converter` the incorrect HTML is produced.

Both the CodePen and node-quill-converter are using the same version (1.3.6) of Quill. Albeit CodePen is using the CloudFare CDN and node-quill-converter using the NPM package.

## Next steps
I will continue to test differences between browser and JSDOM Quill instances. I'll be in touch.

**Comment by kasparkallas** [comment]
I replaced the MutationObserver polyfill with [this one](https://github.com/megawac/MutationObserver.js) and it seemed to work. Can you please confirm?

**Comment by kasparkallas** [comment]
Posting another related issue here. `convertHtmlToDelta` with list items did not work ideally as well. But I noticed that when I opened the resulting Delta in the Quill editor and saved it again the resulting Delta was correct.

So the fix was to replace:
```
exports.convertHtmlToDelta = (html) => {
  var delta = QUILL.clipboard.convert(html);
  QUILL.setContents(delta);
  return QUILL.getContents();
};
```
with:
```

```

**Comment by joelcolucci** [comment]
Nice find @kasparkallas . I've tested with the recommended Polyfill and the conversion to HTML works as expected.

I'll patch this and release shortly.

**Comment by joelcolucci** [comment]
@kasparkallas v0.3.2 includes the fix for this issue and has been published to NPM.

Thank you for your time and assistance!
